---
name: Build

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "10 1 * * 0"

jobs:
  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build amd64 and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            BASE_IMAGE=v1.14-debian-1
          tags: ${{ github.repository }}:latest

      - name: Build amr64 and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amr64
          push: true
          build-args: |
            BASE_IMAGE=v1.14-debian-arm64-1
          tags: ${{ github.repository }}:latest
