name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images.
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          build-args: |
            BASE_IMAGE=fluent/fluentd:v1.15.3-debian-1.2
          tags: ${{ github.repository }}:v1.15.3-debian-1.2
